import { TameCell, CornerClass } from './tameData';

/**
 * The three rolling tessellations of tame polyhedra.
 *
 * Each cell is a triangle with corners A, B, C; reflecting it across its edges tiles the
 * plane. The rotation group of that tiling is the rolling (holonomy) group of the
 * polyhedron, and every corner of the tiling has a class A, B or C: a vertex of the
 * polyhedron of class X always lands on a corner of class X while rolling.
 *
 *   (2,4,4): 45-45-90 triangle, legs 1        (square lattice with alternating diagonals)
 *   (2,3,6): 30-60-90 triangle, legs 1, √3    (kisrhombille: triangular lattice + medians)
 *   (3,3,3): equilateral triangle, side 1     (triangular lattice)
 *
 * "Standard coordinates" (sx, sy) are the plane coordinates in which the base cell sits
 * at C = (0,0), A = (1,0). The app maps them to the floor as world (sx, 0, sy).
 */
export type Vec2 = [number, number];

const SQ3 = Math.sqrt(3);

export const CELL_BASE: Record<TameCell, Record<CornerClass, Vec2>> = {
  '(2,4,4)': { C: [0, 0], A: [1, 0], B: [0, 1] },
  '(2,3,6)': { C: [0, 0], A: [1, 0], B: [0, SQ3] },
  '(3,3,3)': { C: [0, 0], A: [1, 0], B: [0.5, SQ3 / 2] },
};

export const CELL_DESCRIPTION: Record<TameCell, string> = {
  '(2,4,4)': 'square cell (45-45-90 triangles)',
  '(2,3,6)': 'hexagonal cell (30-60-90 triangles)',
  '(3,3,3)': 'triangular cell (equilateral triangles)',
};

/** Corner class colours (same as the handoff figures: A red, B blue, C green). */
export const CLASS_COLORS: Record<CornerClass, string> = {
  A: '#e74c3c',
  B: '#3b82f6',
  C: '#27ae60',
};

/** Cell tints by orientation (front = positively oriented A→B→C). */
export const CELL_TINT_FRONT = '#5fb8b0';
export const CELL_TINT_BACK = '#a98bd2';
export const FLOOR_TINT_FRONT = '#7cc6c0';
export const FLOOR_TINT_BACK = '#b9a2d8';

export interface CellTriangle {
  corners: Record<CornerClass, Vec2>;
  front: boolean;
}

export interface CellCorner {
  pos: Vec2;
  cls: CornerClass;
}

export interface BBox { minX: number; minY: number; maxX: number; maxY: number }

const EDGES: [CornerClass, CornerClass, CornerClass][] = [
  ['A', 'B', 'C'],
  ['B', 'C', 'A'],
  ['C', 'A', 'B'],
];

function reflect(p: Vec2, a: Vec2, b: Vec2): Vec2 {
  let dx = b[0] - a[0], dy = b[1] - a[1];
  const len = Math.hypot(dx, dy);
  dx /= len; dy /= len;
  const vx = p[0] - a[0], vy = p[1] - a[1];
  const d = vx * dx + vy * dy;
  return [a[0] + 2 * d * dx - vx, a[1] + 2 * d * dy - vy];
}

function orient(t: Record<CornerClass, Vec2>): boolean {
  const ux = t.B[0] - t.A[0], uy = t.B[1] - t.A[1];
  const vx = t.C[0] - t.A[0], vy = t.C[1] - t.A[1];
  return ux * vy - uy * vx > 0;
}

function triKey(t: Record<CornerClass, Vec2>): string {
  return (['A', 'B', 'C'] as CornerClass[])
    .map(L => `${t[L][0].toFixed(4)},${t[L][1].toFixed(4)}`)
    .sort()
    .join('|');
}

/**
 * All cells of the tiling whose centroid lies within the bounding box (plus a margin),
 * generated by reflecting the base cell across its edges.
 */
export function generateCellTiling(cell: TameCell, bbox: BBox, margin = 1): CellTriangle[] {
  const base = CELL_BASE[cell];
  const start: Record<CornerClass, Vec2> = { A: [...base.A], B: [...base.B], C: [...base.C] };
  const seen = new Set<string>([triKey(start)]);
  const out: CellTriangle[] = [{ corners: start, front: orient(start) }];
  const queue: Record<CornerClass, Vec2>[] = [start];
  const minX = bbox.minX - margin, maxX = bbox.maxX + margin;
  const minY = bbox.minY - margin, maxY = bbox.maxY + margin;

  while (queue.length) {
    const t = queue.pop()!;
    for (const [a, b, c] of EDGES) {
      const t2 = { ...t, [c]: reflect(t[c], t[a], t[b]) } as Record<CornerClass, Vec2>;
      const cx = (t2.A[0] + t2.B[0] + t2.C[0]) / 3;
      const cy = (t2.A[1] + t2.B[1] + t2.C[1]) / 3;
      if (cx < minX || cx > maxX || cy < minY || cy > maxY) continue;
      const k = triKey(t2);
      if (seen.has(k)) continue;
      seen.add(k);
      out.push({ corners: t2, front: orient(t2) });
      queue.push(t2);
    }
  }
  return out;
}

/** Unique corners of a set of cells, with their class. */
export function tilingCorners(tris: CellTriangle[]): CellCorner[] {
  const map = new Map<string, CellCorner>();
  for (const t of tris) {
    for (const L of ['A', 'B', 'C'] as CornerClass[]) {
      const p = t.corners[L];
      const k = `${p[0].toFixed(4)},${p[1].toFixed(4)}`;
      if (!map.has(k)) map.set(k, { pos: p, cls: L });
    }
  }
  return [...map.values()];
}

export function signedArea(poly: Vec2[]): number {
  let a = 0;
  for (let i = 0; i < poly.length; i++) {
    const p = poly[i], q = poly[(i + 1) % poly.length];
    a += p[0] * q[1] - q[0] * p[1];
  }
  return a / 2;
}

export function ensureCCW(poly: Vec2[]): Vec2[] {
  return signedArea(poly) < 0 ? [...poly].reverse() : poly;
}

/** Sutherland–Hodgman clipping of a convex polygon against a convex CCW polygon. */
export function clipConvex(subject: Vec2[], clip: Vec2[]): Vec2[] {
  let output = ensureCCW(subject);
  const clipper = ensureCCW(clip);
  for (let i = 0; i < clipper.length && output.length > 0; i++) {
    const a = clipper[i], b = clipper[(i + 1) % clipper.length];
    const ex = b[0] - a[0], ey = b[1] - a[1];
    const inside = (p: Vec2) => ex * (p[1] - a[1]) - ey * (p[0] - a[0]) >= -1e-9;
    const input = output;
    output = [];
    for (let j = 0; j < input.length; j++) {
      const cur = input[j], prev = input[(j + input.length - 1) % input.length];
      const curIn = inside(cur), prevIn = inside(prev);
      if (curIn) {
        if (!prevIn) output.push(intersect(prev, cur, a, b));
        output.push(cur);
      } else if (prevIn) {
        output.push(intersect(prev, cur, a, b));
      }
    }
  }
  // drop duplicate consecutive points
  const cleaned: Vec2[] = [];
  for (const p of output) {
    const last = cleaned[cleaned.length - 1];
    if (!last || Math.hypot(last[0] - p[0], last[1] - p[1]) > 1e-7) cleaned.push(p);
  }
  if (cleaned.length > 1) {
    const f = cleaned[0], l = cleaned[cleaned.length - 1];
    if (Math.hypot(f[0] - l[0], f[1] - l[1]) < 1e-7) cleaned.pop();
  }
  return cleaned;
}

function intersect(p: Vec2, q: Vec2, a: Vec2, b: Vec2): Vec2 {
  const dx = q[0] - p[0], dy = q[1] - p[1];
  const ex = b[0] - a[0], ey = b[1] - a[1];
  const den = dx * ey - dy * ex;
  if (Math.abs(den) < 1e-12) return q;
  const t = ((a[0] - p[0]) * ey - (a[1] - p[1]) * ex) / den;
  return [p[0] + t * dx, p[1] + t * dy];
}

/** Point in (or on the boundary of) a convex CCW polygon, with tolerance. */
export function pointInConvex(p: Vec2, poly: Vec2[], tol = 1e-5): boolean {
  for (let i = 0; i < poly.length; i++) {
    const a = poly[i], b = poly[(i + 1) % poly.length];
    const ex = b[0] - a[0], ey = b[1] - a[1];
    const len = Math.hypot(ex, ey) || 1;
    if ((ex * (p[1] - a[1]) - ey * (p[0] - a[0])) / len < -tol) return false;
  }
  return true;
}

export function bboxOf(poly: Vec2[]): BBox {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const [x, y] of poly) {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return { minX, minY, maxX, maxY };
}
