import { Vector3, Quaternion, Matrix4 } from 'three';
import { PolyhedronDefinition, FaceData, SurfaceCell, SurfaceMark } from './PolyhedronDefinition';
import { TAME_SURFACES, TameSurfaceData, TameShapeId } from './tameData';
import {
  CLASS_COLORS, CELL_TINT_FRONT, CELL_TINT_BACK,
  generateCellTiling, tilingCorners, clipConvex, ensureCCW, pointInConvex, bboxOf, signedArea, Vec2,
} from './cellTiling';

/**
 * Tame polyhedra: convex polyhedra whose rolling group is discrete, hence with bounded
 * max overlap thickness K. The geometry and the lattice alignment come from
 * `tameData.ts` (generated by scripts/gen_tame_data.py from the docs/ handoff).
 *
 * Every face carries an affine frame mapping the standard coordinates of the cell tiling
 * to points of that face. Face 1 is placed on the floor so that standard coordinates
 * (sx, sy) coincide with world (sx, 0, sy); since the rolling group is a symmetry group
 * of the tiling, every later face lands aligned with the floor tiling too.
 */
export function createTamePolyhedron(data: TameSurfaceData): PolyhedronDefinition {
  const vertices = data.vertices.map(v => new Vector3(v[0], v[1], v[2]));

  const faces: FaceData[] = data.faces.map((f, i) => {
    const verts = f.map(k => vertices[k]);
    const center = verts.reduce((acc, v) => acc.add(v), new Vector3()).divideScalar(verts.length);
    const normal = new Vector3()
      .subVectors(verts[1], verts[0])
      .cross(new Vector3().subVectors(verts[2], verts[1]))
      .normalize();
    return { index: i + 1, center, normal, vertices: verts };
  });

  const frames = data.frames.map(fr => ({
    o: new Vector3(fr.o[0], fr.o[1], fr.o[2]),
    ex: new Vector3(fr.ex[0], fr.ex[1], fr.ex[2]),
    ey: new Vector3(fr.ey[0], fr.ey[1], fr.ey[2]),
  }));
  const faceStd: Vec2[][] = data.faceStd.map(f => ensureCCW(f.map(p => [p[0], p[1]] as Vec2)));

  // Directed edge (u,v) -> face index, to find the face across an edge
  const edgeFace = new Map<string, number>();
  data.faces.forEach((f, i) => f.forEach((u, k) => edgeFace.set(`${u},${f[(k + 1) % f.length]}`, i)));
  const adjacentFace = (faceIdx: number, k: number): number => {
    const f = data.faces[faceIdx];
    return edgeFace.get(`${f[(k + 1) % f.length]},${f[k]}`)!;
  };

  // Initial placement: face 1 flat on the floor, standard coords (sx, sy) -> world (sx, 0, sy).
  // The frame (ex, ey, n) of face 1 is right-handed as seen from outside, so n maps to -y.
  const f0 = frames[0];
  const ex = f0.ex.clone().normalize();
  const ey = f0.ey.clone().normalize();
  const n0 = new Vector3().crossVectors(ex, ey).normalize();
  const mSource = new Matrix4().makeBasis(ex, ey, n0);
  const mTarget = new Matrix4().makeBasis(new Vector3(1, 0, 0), new Vector3(0, 0, 1), new Vector3(0, -1, 0));
  const initialQuaternion = new Quaternion().setFromRotationMatrix(mTarget.clone().multiply(mSource.clone().transpose()));
  const initialPosition = f0.o.clone().applyQuaternion(initialQuaternion).negate();

  const inradius = Math.abs(faces[0].vertices[0].dot(faces[0].normal));
  const dihedralAngle = data.flat ? 0 : Math.PI - faces[0].normal.angleTo(faces[adjacentFace(0, 0)].normal);

  // Cells and lattice corners painted on the surface (computed lazily, once)
  let cellsCache: SurfaceCell[] | null = null;
  let marksCache: SurfaceMark[] | null = null;
  const computeDecoration = () => {
    const cells: SurfaceCell[] = [];
    const marks: SurfaceMark[] = [];
    const nearAny = (p: Vector3, list: Vector3[]) => list.some(q => q.distanceTo(p) < 1e-3);
    faces.forEach((face, j) => {
      const poly = faceStd[j];
      const fr = frames[j];
      const to3d = (p: Vec2) => fr.o.clone().addScaledVector(fr.ex, p[0]).addScaledVector(fr.ey, p[1]);
      const tris = generateCellTiling(data.cell, bboxOf(poly), 1.5);
      for (const t of tris) {
        const piece = clipConvex([t.corners.A, t.corners.B, t.corners.C], poly);
        if (piece.length < 3 || Math.abs(signedArea(piece)) < 1e-6) continue;
        cells.push({ faceIndex: j + 1, vertices: piece.map(to3d), normal: face.normal, front: t.front });
      }
      for (const c of tilingCorners(tris)) {
        if (!pointInConvex(c.pos, poly, 1e-4)) continue;
        const p = to3d(c.pos);
        if (nearAny(p, vertices) || nearAny(p, marks.map(m => m.position))) continue;
        marks.push({ position: p, cls: c.cls, color: CLASS_COLORS[c.cls] });
      }
    });
    cellsCache = cells;
    marksCache = marks;
  };

  return {
    id: data.id,
    name: data.display,
    faceCount: faces.length,
    vertexCount: vertices.length,

    vertices,
    faceIndices: data.faces,
    // NOTE: for irregular polyhedra the face centroid direction is not the face normal;
    // we store the outward normals here (consumers should prefer getFaces()[i].normal).
    faceCenters: faces.map(f => f.normal.clone()),

    inradius,
    dihedralAngle,
    rollAngle: Math.PI - dihedralAngle, // per-edge angles are computed in Simulation
    edgeLength: 1,

    facePalette: [CELL_TINT_FRONT, CELL_TINT_BACK],
    faceLabelSize: 0.18,
    vertexSphereRadius: 0.06,

    initialPosition,
    initialQuaternion,

    latticeType: 'cell',
    movementSectors: 0,
    sectorAngle: 0,

    tame: data,
    showVertexLabels: true,

    getVertices() { return vertices; },
    getFaces() { return faces; },
    getBottomVertexCount() { return faces[0].vertices.length; },

    getVertexColor(index: number): string {
      return CLASS_COLORS[data.vertexClasses[index]];
    },
    getFaceColor(): string {
      return '#e2e8f0';
    },
    getLatticeVertexColor(): string {
      return '#94a3b8';
    },

    getOrientationLabel(): string {
      return '';
    },
    getMoveData(_angle: number, edge?: [number, number]) {
      const label = edge ? `${edge[0] + 1}–${edge[1] + 1}` : 'ROLL';
      return { label, delta: { u: 0, v: 0 } };
    },

    getSurfaceCells() {
      if (!cellsCache) computeDecoration();
      return cellsCache!;
    },
    getSurfaceMarks() {
      if (!marksCache) computeDecoration();
      return marksCache!;
    },
  };
}

export const TAME_POLYHEDRA = Object.fromEntries(
  TAME_SURFACES.map(d => [d.id, createTamePolyhedron(d)])
) as Record<TameShapeId, PolyhedronDefinition>;
