"""Decision procedure: given a convex polyhedron (vertices X, faces as CCW vertex lists), decide tame/wild and
compute the max overlap thickness K = area(P)/area(R^2/H) where H is the holonomy (rolling) group.
Method: unfold faces along a spanning tree (placements in the plane); every non-tree face adjacency gives a
rigid motion g (rotation angle, translation) = holonomy of the corresponding loop. H = <g_e>.
Tame iff rotation angles are multiples of 360/n (n in {1,2,3,4,6}) and the translation subgroup T(H) is a lattice.
T(H) is generated by: g^n_i (n_i = order of rotation part), g_i g_j^-1 with equal rotation parts, and conjugates
by coset representatives. Lattice test: rank of Z-span <= 2 via rational relations (exact arithmetic on
rounded floats with a tolerance; entries are in Q(sqrt3) here so we use LLL-free approach: check that all
translations are Q-combinations of two of them with small denominators)."""
import numpy as np, math, itertools
from fractions import Fraction
def rot(th): c,s=math.cos(th),math.sin(th); return np.array([[c,-s],[s,c]])
def unfold(X,faces):
    X=np.array(X,float); m=len(faces)
    shared={}
    for i in range(m):
        for j in range(i+1,m):
            common=[v for v in faces[i] if v in faces[j]]
            if len(common)==2: shared[(i,j)]=tuple(common)
    def local2d(f):
        a=X[f[0]]; e1=X[f[1]]-a; e1/=np.linalg.norm(e1)
        nrm=np.cross(X[f[1]]-X[f[0]],X[f[2]]-X[f[1]]); nrm/=np.linalg.norm(nrm); e2=np.cross(nrm,e1)
        return {v:np.array([np.dot(X[v]-a,e1),np.dot(X[v]-a,e2)]) for v in f}
    loc=[local2d(f) for f in faces]
    adj={i:[] for i in range(m)}
    for (i,j) in shared: adj[i].append(j); adj[j].append(i)
    placed={0:(np.eye(2),np.zeros(2))}; q=[0]; tree=set()
    def place_from(cur,j):
        u,v=shared[(min(cur,j),max(cur,j))]
        M,t=placed[cur]; P={vv:M@loc[cur][vv]+t for vv in faces[cur]}; Lc=loc[j]
        d1=Lc[v]-Lc[u]; d2=P[v]-P[u]
        th=math.atan2(d2[1],d2[0])-math.atan2(d1[1],d1[0]); R=rot(th)
        return (R, P[u]-R@Lc[u])
    while q:
        cur=q.pop(0)
        for j in adj[cur]:
            if j in placed: continue
            placed[j]=place_from(cur,j); tree.add(frozenset((cur,j))); q.append(j)
    # holonomy generators from non-tree adjacencies: motion taking placed_j to the placement of j reached via i
    gens=[]
    for (i,j) in shared:
        if frozenset((i,j)) in tree: continue
        R2,t2=place_from(i,j); R1,t1=placed[j]
        # g maps R1 x + t1  ->  R2 x + t2 :  g = (R2 R1^-1, t2 - R2 R1^-1 t1)
        G=R2@R1.T; gens.append((G,t2-G@t1))
    area=0
    for f in faces:
        P=loc[f is None or faces.index(f)] if False else None
    def polyarea(pts):
        return 0.5*abs(sum(pts[k][0]*pts[(k+1)%len(pts)][1]-pts[(k+1)%len(pts)][0]*pts[k][1] for k in range(len(pts))))
    area=sum(polyarea([loc[i][v] for v in faces[i]]) for i in range(m))
    return gens,area
def angle_of(G): return math.degrees(math.atan2(G[1,0],G[0,0]))%360
def rat_rank2(vecs,tol=1e-5,maxden=200):
    """check that all vecs are Q-combinations of two independent ones; return (ok, basis u,v, list of coefficient pairs)"""
    vecs=[np.array(v,float) for v in vecs if np.linalg.norm(v)>tol]
    if not vecs: return True,None,None,[]
    u=vecs[0]; v=None
    for w in vecs[1:]:
        if abs(u[0]*w[1]-u[1]*w[0])>tol: v=w;break
    if v is None:
        # all parallel: check ratios rational
        rs=[np.dot(w,u)/np.dot(u,u) for w in vecs]
        ok=all(abs(r-Fraction(r).limit_denominator(maxden))<tol for r in rs)
        return ok,u,None,rs
    M=np.array([u,v]).T; coeffs=[]
    for w in vecs:
        c=np.linalg.solve(M,w)
        fr=[Fraction(x).limit_denominator(maxden) for x in c]
        if any(abs(float(f)-x)>tol for f,x in zip(fr,c)): return False,u,v,None
        coeffs.append(fr)
    return True,u,v,coeffs
def lattice_covol(u,v,coeffs):
    """covolume of the lattice generated by the vectors sum coeff*u,v"""
    # lattice generated by rational combos: find Z-basis via Hermite on the rational coefficient matrix
    from math import gcd
    den=1
    for c in coeffs:
        for f in c: den=den*f.denominator//gcd(den,f.denominator)
    rows=[[int(f*den) for f in c] for c in coeffs]
    # integer lattice generated by rows in Z^2; covolume = gcd of 2x2 minors ... compute via HNF
    import sympy
    Mx=sympy.Matrix(rows)
    H=Mx.T  # columns are vectors
    # Smith normal form diag product = index of lattice in Z^2 if rank 2
    from sympy.matrices.normalforms import smith_normal_form
    S=smith_normal_form(H,domain=sympy.ZZ)
    d=1; r=0
    for i in range(min(S.shape)):
        if S[i,i]!=0: d*=abs(int(S[i,i])); r+=1
    if r<2: return None
    return d*abs(u[0]*v[1]-u[1]*v[0])/den**2
def analyze(X,faces,verbose=True):
    gens,area=unfold(X,faces)
    angs=[angle_of(G) for G,t in gens]
    # rotation orders
    def order(a):
        for n in (1,2,3,4,6):
            m=(a*n)%360
            if min(m,360-m)<1e-3: return n
        return None
    ords=[order(a) for a in angs]
    if any(o is None for o in ords):
        if verbose: print("WILD: a loop rotation is not a multiple of 60 or 90 degrees:",[round(a,3) for a in angs])
        return None
    # rotation group order n = lcm of orders
    n=1
    for o in ords: n=n*o//math.gcd(n,o)
    # translation subgroup T(H) via Schreier's lemma: H -> C_n (rotation parts); coset reps by BFS
    def mul(g,h): return (g[0]@h[0], g[0]@h[1]+g[1])
    def inv(g): return (g[0].T, -g[0].T@g[1])
    idg=(np.eye(2),np.zeros(2))
    def rkey(g): return int(round(angle_of(g[0])*n/360))%n
    reps={0:idg}; frontier=[0]
    while frontier:
        r0=frontier.pop(0)
        for g in gens:
            r1=(r0+rkey(g))%n
            if r1 not in reps: reps[r1]=mul(g,reps[r0]); frontier.append(r1)
    if len(reps)<n:
        n=len(reps)  # rotation part actually smaller
    trans=[]
    for r0,h in reps.items():
        for g in gens:
            r1=(r0+rkey(g))%n
            if r1 not in reps: continue
            sg=mul(inv(reps[r1]),mul(g,h))   # h_{r1}^-1 g h_{r0}: trivial rotation
            trans.append(sg[1])
    ok,u,v,coeffs=rat_rank2(trans)
    if not ok:
        if verbose: print("WILD: translation part of the rolling group is not a lattice")
        return None
    if v is None:
        if verbose: print("degenerate: all translations parallel (should not happen for closed surface)")
        return None
    covol=lattice_covol(u,v,coeffs)
    K=area*n/covol
    if verbose: print(f"TAME: rotation order n={n}, lattice covolume={covol:.6f}, area={area:.6f}, thickness K = area*n/covol = {K:.6f}")
    return K
if __name__=="__main__":
    import pickle
    from draw3 import merged_faces
    # validate on the solved solids P1..P16
    from draw6 import NAMES
    for idx in range(16):
        r,Tg,faces,X,tf=pickle.load(open(f'sol_{idx}.pkl','rb'))
        polys=merged_faces(X,tf); cen=X.mean(0); out=[]
        for f in polys:
            a,b,c=[X[v] for v in f[:3]]; nn=np.cross(b-a,c-a)
            out.append(f[::-1] if np.dot(nn,a-cen)<0 else f)
        print(NAMES[idx][0],"expected K=",r['K'],end=": ")
        analyze(X,out)
